### ISSUE TITLE
We could add some animations

### ISSUE THREAD

**Issue by yogirajbshinde21** [ortonb110/Telescope#1]
We could add some animations of satellites moving around in infinite loop which will increase weight of UI of your website.
![Screenshot 2024-06-21 190635](https://github.com/ortonb110/Telescope/assets/84953719/8ae6e86f-cf66-4abe-91d2-f195fb590cea)

**Comment by ortonb110** [comment]
This is true and I agree with you, do you want to join so we get this done?

**Comment by yogirajbshinde21** [comment]
@ortonb110 I would love to join & make a contribution in this!
